services:
  app:
    image: bitonic
    build:
      context: .
    ports:
      - "3000:3000"
    # platform: linux/amd64
    depends_on: 
      - redis
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"